TB_PLAYER_LIST = {
	'id': 1,
	'name': 2,
	'full name': 3,
	'email': 4,
}

TB_GAME = {
	'id': 1,
	'date': 2,
	'name': 3,
	'game progress': 4,
	'p1': 5,
	'p2': 6,
	'p3': 7,
	'p4': 8,
	'aka': 9,
	'uma position 1': 10,
	'uma position 2': 11,
	'uma position 3': 12,
	'uma position 4': 13,
	'oka': 14,
	'final score p1': 15,
	'final score p2': 16,
	'final score p3': 17,
	'final score p4': 18,
	'final position p1': 19,
	'final position p2': 20,
	'final position p3': 21,
	'final position p4': 22,
	'penalty p1': 23,
	'penalty p2': 24,
	'penalty p3': 25,
	'penalty p4': 26,
}

TB_HAND = {
	'id': 1,
	'game id': 2,
	'hand num': 3,
	'wind': 4,
	'round num': 5,
	'honba': 6,
	'outcome': 7,
	'han': 8,
	'fu': 9,
	'value': 10,
}

TB_HAND_OUTCOME = {
	'id': 1,
	'hand id': 2,
	'game id': 3,
	'player id': 4,
	'position': 5,
	'dealer': 6,
	'outcome': 7,
	'draw outcome': 8,
	'riichi': 9,
	'start score': 10,
	'end score': 11,
	'score change': 12,
	'chombo': 13,
}